.PHONY:	all clean

CROSS_COMPILE := oldland-elf-
AS := $(CROSS_COMPILE)as
LD := $(CROSS_COMPILE)ld
OBJCOPY := $(CROSS_COMPILE)objcopy

include Makefile

all:	$(TESTNAME).bin

%.o:	%.S
	$(AS) $< -o $@

%.o:	%.s
	$(AS) $< -o $@

%.bin:	%
	$(OBJCOPY) $< $@ -O binary

$(TESTNAME):	$(OBJS)
	$(LD) $< -o $@ -x $(PWD)/target/sim.x

clean:
	rm -rf $(OBJS) $(TESTNAME) $(TESTNAME).bin
