#!/usr/bin/env python
from multiprocessing import Process
import os
import subprocess
import sys

try:
    from termcolor import cprint
except ImportError:
    def cprint(msg, color):
        print(msg)

from junit_xml import TestSuite, TestCase

def find_test_files():
    for _, _, filenames in os.walk(TEST_PATH):
        def is_test(fn):
            return fn.endswith('.lua') and fn != 'common.lua'
        return filter(is_test, filenames)

TEST_PATH = '%TEST_PATH%'
SIMULATORS = 'oldland-sim oldland-rtlsim'.split()
TEST_FILES = find_test_files()
SIM_ARGS = {
    'oldland-rtlsim': ['--bootrom', 'sim.hex']
}
FIFO_PATH = '/tmp/oldland-test.{0}'.format(os.getpid())

def sim_runner(kargs):
    sim_env = dict(os.environ)
    sim_env['SIM_NOTIFY_FIFO'] = FIFO_PATH

    subprocess.Popen(list(kargs), env = sim_env).communicate()

def wait_for_sim():
    fd = os.open(FIFO_PATH, os.O_RDONLY)
    os.read(fd, 1)
    os.close(fd)

def run_test(simulator, test_file):
    try:
        os.unlink(FIFO_PATH)
    except:
        pass
    os.mkfifo(FIFO_PATH)

    simargs = [simulator]
    if simulator in SIM_ARGS:
        simargs += SIM_ARGS[simulator]
    runner = Process(target = sim_runner, args = (simargs,))
    runner.start()

    wait_for_sim()

    debugger = subprocess.Popen(['oldland-debug', '-x',
                                os.path.join(TEST_PATH, test_file)],
                                stdout = subprocess.PIPE,
                                stderr = subprocess.PIPE, cwd = TEST_PATH)
    stdout, stderr = debugger.communicate()

    runner.join()

    tc = TestCase(test_file, test_file, 0, stdout)
    if debugger.returncode:
        tc.add_failure_info('test returned {0}'.format(debugger.returncode),
                            stderr)

    cprint('{0}::{1}'.format(simulator, test_file),
           'red' if debugger.returncode else 'green')
    os.unlink(FIFO_PATH)

    return tc

def main():
    suites = []
    for sim in SIMULATORS:
        cases = []
        for t in TEST_FILES:
            cases.append(run_test(sim, t))
        suites.append(TestSuite(sim, cases))

    with open('oldland-test.xml', 'w') as output:
        output.write(TestSuite.to_xml_string(suites))

    all_cases = [c for ts in suites for c in ts.test_cases]
    num_failures = len(filter(lambda x: x.is_failure(), all_cases))
    print '\n{0}/{1} failures'.format(num_failures, len(all_cases))

if __name__ == '__main__':
    sys.exit(main())
