// megafunction wizard: %ROM: 2-PORT%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: altsyncram 

// ============================================================
// File Name: bootrom.v
// Megafunction Name(s):
// 			altsyncram
//
// Simulation Library Files(s):
// 			altera_mf
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 13.0.0 Build 156 04/24/2013 SJ Web Edition
// ************************************************************


//Copyright (C) 1991-2013 Altera Corporation
//Your use of Altera Corporation's design tools, logic functions 
//and other software and tools, and its AMPP partner logic 
//functions, and any output files from any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Altera Program License 
//Subscription Agreement, Altera MegaCore Function License 
//Agreement, or other applicable license agreement, including, 
//without limitation, that your use is for the sole purpose of 
//programming logic devices manufactured by Altera and sold by 
//Altera or its authorized distributors.  Please refer to the 
//applicable agreement for further details.


//altsyncram ADDRESS_REG_B="CLOCK0" CLOCK_ENABLE_INPUT_A="BYPASS" CLOCK_ENABLE_INPUT_B="BYPASS" CLOCK_ENABLE_OUTPUT_A="BYPASS" CLOCK_ENABLE_OUTPUT_B="BYPASS" DEVICE_FAMILY="Cyclone IV E" INDATA_REG_B="CLOCK0" INIT_FILE="../bootrom.hex" NUMWORDS_A=64 NUMWORDS_B=64 OPERATION_MODE="BIDIR_DUAL_PORT" OUTDATA_ACLR_A="NONE" OUTDATA_ACLR_B="NONE" OUTDATA_REG_A="UNREGISTERED" OUTDATA_REG_B="UNREGISTERED" POWER_UP_UNINITIALIZED="FALSE" WIDTH_A=32 WIDTH_B=32 WIDTH_BYTEENA_A=1 WIDTH_BYTEENA_B=1 WIDTHAD_A=6 WIDTHAD_B=6 WRCONTROL_WRADDRESS_REG_B="CLOCK0" address_a address_b clock0 data_a data_b q_a q_b wren_a wren_b
//VERSION_BEGIN 13.0 cbx_altsyncram 2013:04:24:18:16:58:SJ cbx_cycloneii 2013:04:24:18:16:58:SJ cbx_lpm_add_sub 2013:04:24:18:16:58:SJ cbx_lpm_compare 2013:04:24:18:16:58:SJ cbx_lpm_decode 2013:04:24:18:16:58:SJ cbx_lpm_mux 2013:04:24:18:16:58:SJ cbx_mgl 2013:04:24:18:18:51:SJ cbx_stratix 2013:04:24:18:16:58:SJ cbx_stratixii 2013:04:24:18:16:58:SJ cbx_stratixiii 2013:04:24:18:16:58:SJ cbx_stratixv 2013:04:24:18:16:58:SJ cbx_util_mgl 2013:04:24:18:16:58:SJ  VERSION_END
// synthesis VERILOG_INPUT_VERSION VERILOG_2001
// altera message_off 10463


//synthesis_resources = M9K 2 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
(* ALTERA_ATTRIBUTE = {"OPTIMIZE_POWER_DURING_SYNTHESIS=NORMAL_COMPILATION"} *)
module  bootrom_altsyncram
	( 
	address_a,
	address_b,
	clock0,
	data_a,
	data_b,
	q_a,
	q_b,
	wren_a,
	wren_b) /* synthesis synthesis_clearbox=1 */;
	input   [5:0]  address_a;
	input   [5:0]  address_b;
	input   clock0;
	input   [31:0]  data_a;
	input   [31:0]  data_b;
	output   [31:0]  q_a;
	output   [31:0]  q_b;
	input   wren_a;
	input   wren_b;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri1   [5:0]  address_b;
	tri1   clock0;
	tri1   [31:0]  data_a;
	tri1   [31:0]  data_b;
	tri0   wren_a;
	tri0   wren_b;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [0:0]   wire_ram_block1a_0portadataout;
	wire  [0:0]   wire_ram_block1a_1portadataout;
	wire  [0:0]   wire_ram_block1a_2portadataout;
	wire  [0:0]   wire_ram_block1a_3portadataout;
	wire  [0:0]   wire_ram_block1a_4portadataout;
	wire  [0:0]   wire_ram_block1a_5portadataout;
	wire  [0:0]   wire_ram_block1a_6portadataout;
	wire  [0:0]   wire_ram_block1a_7portadataout;
	wire  [0:0]   wire_ram_block1a_8portadataout;
	wire  [0:0]   wire_ram_block1a_9portadataout;
	wire  [0:0]   wire_ram_block1a_10portadataout;
	wire  [0:0]   wire_ram_block1a_11portadataout;
	wire  [0:0]   wire_ram_block1a_12portadataout;
	wire  [0:0]   wire_ram_block1a_13portadataout;
	wire  [0:0]   wire_ram_block1a_14portadataout;
	wire  [0:0]   wire_ram_block1a_15portadataout;
	wire  [0:0]   wire_ram_block1a_16portadataout;
	wire  [0:0]   wire_ram_block1a_17portadataout;
	wire  [0:0]   wire_ram_block1a_18portadataout;
	wire  [0:0]   wire_ram_block1a_19portadataout;
	wire  [0:0]   wire_ram_block1a_20portadataout;
	wire  [0:0]   wire_ram_block1a_21portadataout;
	wire  [0:0]   wire_ram_block1a_22portadataout;
	wire  [0:0]   wire_ram_block1a_23portadataout;
	wire  [0:0]   wire_ram_block1a_24portadataout;
	wire  [0:0]   wire_ram_block1a_25portadataout;
	wire  [0:0]   wire_ram_block1a_26portadataout;
	wire  [0:0]   wire_ram_block1a_27portadataout;
	wire  [0:0]   wire_ram_block1a_28portadataout;
	wire  [0:0]   wire_ram_block1a_29portadataout;
	wire  [0:0]   wire_ram_block1a_30portadataout;
	wire  [0:0]   wire_ram_block1a_31portadataout;
	wire  [0:0]   wire_ram_block1a_0portbdataout;
	wire  [0:0]   wire_ram_block1a_1portbdataout;
	wire  [0:0]   wire_ram_block1a_2portbdataout;
	wire  [0:0]   wire_ram_block1a_3portbdataout;
	wire  [0:0]   wire_ram_block1a_4portbdataout;
	wire  [0:0]   wire_ram_block1a_5portbdataout;
	wire  [0:0]   wire_ram_block1a_6portbdataout;
	wire  [0:0]   wire_ram_block1a_7portbdataout;
	wire  [0:0]   wire_ram_block1a_8portbdataout;
	wire  [0:0]   wire_ram_block1a_9portbdataout;
	wire  [0:0]   wire_ram_block1a_10portbdataout;
	wire  [0:0]   wire_ram_block1a_11portbdataout;
	wire  [0:0]   wire_ram_block1a_12portbdataout;
	wire  [0:0]   wire_ram_block1a_13portbdataout;
	wire  [0:0]   wire_ram_block1a_14portbdataout;
	wire  [0:0]   wire_ram_block1a_15portbdataout;
	wire  [0:0]   wire_ram_block1a_16portbdataout;
	wire  [0:0]   wire_ram_block1a_17portbdataout;
	wire  [0:0]   wire_ram_block1a_18portbdataout;
	wire  [0:0]   wire_ram_block1a_19portbdataout;
	wire  [0:0]   wire_ram_block1a_20portbdataout;
	wire  [0:0]   wire_ram_block1a_21portbdataout;
	wire  [0:0]   wire_ram_block1a_22portbdataout;
	wire  [0:0]   wire_ram_block1a_23portbdataout;
	wire  [0:0]   wire_ram_block1a_24portbdataout;
	wire  [0:0]   wire_ram_block1a_25portbdataout;
	wire  [0:0]   wire_ram_block1a_26portbdataout;
	wire  [0:0]   wire_ram_block1a_27portbdataout;
	wire  [0:0]   wire_ram_block1a_28portbdataout;
	wire  [0:0]   wire_ram_block1a_29portbdataout;
	wire  [0:0]   wire_ram_block1a_30portbdataout;
	wire  [0:0]   wire_ram_block1a_31portbdataout;
	wire  [5:0]  address_a_wire;
	wire  [5:0]  address_b_wire;

	cycloneive_ram_block   ram_block1a_0
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[5:0]}),
	.portadatain({data_a[0]}),
	.portadataout(wire_ram_block1a_0portadataout[0:0]),
	.portare(1'b1),
	.portawe(wren_a),
	.portbaddr({address_b_wire[5:0]}),
	.portbdatain({data_b[0]}),
	.portbdataout(wire_ram_block1a_0portbdataout[0:0]),
	.portbre(1'b1),
	.portbwe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_0.clk0_core_clock_enable = "none",
		ram_block1a_0.clk0_input_clock_enable = "none",
		ram_block1a_0.connectivity_checking = "OFF",
		ram_block1a_0.init_file = "../bootrom.hex",
		ram_block1a_0.init_file_layout = "port_a",
		ram_block1a_0.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_0.mem_init0 = 64'h0000000002A8F0A8,
		ram_block1a_0.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_0.operation_mode = "bidir_dual_port",
		ram_block1a_0.port_a_address_width = 6,
		ram_block1a_0.port_a_data_out_clear = "none",
		ram_block1a_0.port_a_data_width = 1,
		ram_block1a_0.port_a_first_address = 0,
		ram_block1a_0.port_a_first_bit_number = 0,
		ram_block1a_0.port_a_last_address = 63,
		ram_block1a_0.port_a_logical_ram_depth = 64,
		ram_block1a_0.port_a_logical_ram_width = 32,
		ram_block1a_0.port_a_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_0.port_b_address_clock = "clock0",
		ram_block1a_0.port_b_address_width = 6,
		ram_block1a_0.port_b_data_in_clock = "clock0",
		ram_block1a_0.port_b_data_out_clear = "none",
		ram_block1a_0.port_b_data_width = 1,
		ram_block1a_0.port_b_first_address = 0,
		ram_block1a_0.port_b_first_bit_number = 0,
		ram_block1a_0.port_b_last_address = 63,
		ram_block1a_0.port_b_logical_ram_depth = 64,
		ram_block1a_0.port_b_logical_ram_width = 32,
		ram_block1a_0.port_b_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_0.port_b_read_enable_clock = "clock0",
		ram_block1a_0.port_b_write_enable_clock = "clock0",
		ram_block1a_0.power_up_uninitialized = "false",
		ram_block1a_0.ram_block_type = "AUTO",
		ram_block1a_0.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_1
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[5:0]}),
	.portadatain({data_a[1]}),
	.portadataout(wire_ram_block1a_1portadataout[0:0]),
	.portare(1'b1),
	.portawe(wren_a),
	.portbaddr({address_b_wire[5:0]}),
	.portbdatain({data_b[1]}),
	.portbdataout(wire_ram_block1a_1portbdataout[0:0]),
	.portbre(1'b1),
	.portbwe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_1.clk0_core_clock_enable = "none",
		ram_block1a_1.clk0_input_clock_enable = "none",
		ram_block1a_1.connectivity_checking = "OFF",
		ram_block1a_1.init_file = "../bootrom.hex",
		ram_block1a_1.init_file_layout = "port_a",
		ram_block1a_1.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_1.mem_init0 = 64'h0000000000C48480,
		ram_block1a_1.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_1.operation_mode = "bidir_dual_port",
		ram_block1a_1.port_a_address_width = 6,
		ram_block1a_1.port_a_data_out_clear = "none",
		ram_block1a_1.port_a_data_width = 1,
		ram_block1a_1.port_a_first_address = 0,
		ram_block1a_1.port_a_first_bit_number = 1,
		ram_block1a_1.port_a_last_address = 63,
		ram_block1a_1.port_a_logical_ram_depth = 64,
		ram_block1a_1.port_a_logical_ram_width = 32,
		ram_block1a_1.port_a_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_1.port_b_address_clock = "clock0",
		ram_block1a_1.port_b_address_width = 6,
		ram_block1a_1.port_b_data_in_clock = "clock0",
		ram_block1a_1.port_b_data_out_clear = "none",
		ram_block1a_1.port_b_data_width = 1,
		ram_block1a_1.port_b_first_address = 0,
		ram_block1a_1.port_b_first_bit_number = 1,
		ram_block1a_1.port_b_last_address = 63,
		ram_block1a_1.port_b_logical_ram_depth = 64,
		ram_block1a_1.port_b_logical_ram_width = 32,
		ram_block1a_1.port_b_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_1.port_b_read_enable_clock = "clock0",
		ram_block1a_1.port_b_write_enable_clock = "clock0",
		ram_block1a_1.power_up_uninitialized = "false",
		ram_block1a_1.ram_block_type = "AUTO",
		ram_block1a_1.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_2
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[5:0]}),
	.portadatain({data_a[2]}),
	.portadataout(wire_ram_block1a_2portadataout[0:0]),
	.portare(1'b1),
	.portawe(wren_a),
	.portbaddr({address_b_wire[5:0]}),
	.portbdatain({data_b[2]}),
	.portbdataout(wire_ram_block1a_2portbdataout[0:0]),
	.portbre(1'b1),
	.portbwe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_2.clk0_core_clock_enable = "none",
		ram_block1a_2.clk0_input_clock_enable = "none",
		ram_block1a_2.connectivity_checking = "OFF",
		ram_block1a_2.init_file = "../bootrom.hex",
		ram_block1a_2.init_file_layout = "port_a",
		ram_block1a_2.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_2.mem_init0 = 64'h0000008043046418,
		ram_block1a_2.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_2.operation_mode = "bidir_dual_port",
		ram_block1a_2.port_a_address_width = 6,
		ram_block1a_2.port_a_data_out_clear = "none",
		ram_block1a_2.port_a_data_width = 1,
		ram_block1a_2.port_a_first_address = 0,
		ram_block1a_2.port_a_first_bit_number = 2,
		ram_block1a_2.port_a_last_address = 63,
		ram_block1a_2.port_a_logical_ram_depth = 64,
		ram_block1a_2.port_a_logical_ram_width = 32,
		ram_block1a_2.port_a_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_2.port_b_address_clock = "clock0",
		ram_block1a_2.port_b_address_width = 6,
		ram_block1a_2.port_b_data_in_clock = "clock0",
		ram_block1a_2.port_b_data_out_clear = "none",
		ram_block1a_2.port_b_data_width = 1,
		ram_block1a_2.port_b_first_address = 0,
		ram_block1a_2.port_b_first_bit_number = 2,
		ram_block1a_2.port_b_last_address = 63,
		ram_block1a_2.port_b_logical_ram_depth = 64,
		ram_block1a_2.port_b_logical_ram_width = 32,
		ram_block1a_2.port_b_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_2.port_b_read_enable_clock = "clock0",
		ram_block1a_2.port_b_write_enable_clock = "clock0",
		ram_block1a_2.power_up_uninitialized = "false",
		ram_block1a_2.ram_block_type = "AUTO",
		ram_block1a_2.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_3
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[5:0]}),
	.portadatain({data_a[3]}),
	.portadataout(wire_ram_block1a_3portadataout[0:0]),
	.portare(1'b1),
	.portawe(wren_a),
	.portbaddr({address_b_wire[5:0]}),
	.portbdatain({data_b[3]}),
	.portbdataout(wire_ram_block1a_3portbdataout[0:0]),
	.portbre(1'b1),
	.portbwe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_3.clk0_core_clock_enable = "none",
		ram_block1a_3.clk0_input_clock_enable = "none",
		ram_block1a_3.connectivity_checking = "OFF",
		ram_block1a_3.init_file = "../bootrom.hex",
		ram_block1a_3.init_file_layout = "port_a",
		ram_block1a_3.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_3.mem_init0 = 64'h00000098CAAC9B7E,
		ram_block1a_3.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_3.operation_mode = "bidir_dual_port",
		ram_block1a_3.port_a_address_width = 6,
		ram_block1a_3.port_a_data_out_clear = "none",
		ram_block1a_3.port_a_data_width = 1,
		ram_block1a_3.port_a_first_address = 0,
		ram_block1a_3.port_a_first_bit_number = 3,
		ram_block1a_3.port_a_last_address = 63,
		ram_block1a_3.port_a_logical_ram_depth = 64,
		ram_block1a_3.port_a_logical_ram_width = 32,
		ram_block1a_3.port_a_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_3.port_b_address_clock = "clock0",
		ram_block1a_3.port_b_address_width = 6,
		ram_block1a_3.port_b_data_in_clock = "clock0",
		ram_block1a_3.port_b_data_out_clear = "none",
		ram_block1a_3.port_b_data_width = 1,
		ram_block1a_3.port_b_first_address = 0,
		ram_block1a_3.port_b_first_bit_number = 3,
		ram_block1a_3.port_b_last_address = 63,
		ram_block1a_3.port_b_logical_ram_depth = 64,
		ram_block1a_3.port_b_logical_ram_width = 32,
		ram_block1a_3.port_b_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_3.port_b_read_enable_clock = "clock0",
		ram_block1a_3.port_b_write_enable_clock = "clock0",
		ram_block1a_3.power_up_uninitialized = "false",
		ram_block1a_3.ram_block_type = "AUTO",
		ram_block1a_3.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_4
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[5:0]}),
	.portadatain({data_a[4]}),
	.portadataout(wire_ram_block1a_4portadataout[0:0]),
	.portare(1'b1),
	.portawe(wren_a),
	.portbaddr({address_b_wire[5:0]}),
	.portbdatain({data_b[4]}),
	.portbdataout(wire_ram_block1a_4portbdataout[0:0]),
	.portbre(1'b1),
	.portbwe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_4.clk0_core_clock_enable = "none",
		ram_block1a_4.clk0_input_clock_enable = "none",
		ram_block1a_4.connectivity_checking = "OFF",
		ram_block1a_4.init_file = "../bootrom.hex",
		ram_block1a_4.init_file_layout = "port_a",
		ram_block1a_4.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_4.mem_init0 = 64'h00000199C8CB349A,
		ram_block1a_4.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_4.operation_mode = "bidir_dual_port",
		ram_block1a_4.port_a_address_width = 6,
		ram_block1a_4.port_a_data_out_clear = "none",
		ram_block1a_4.port_a_data_width = 1,
		ram_block1a_4.port_a_first_address = 0,
		ram_block1a_4.port_a_first_bit_number = 4,
		ram_block1a_4.port_a_last_address = 63,
		ram_block1a_4.port_a_logical_ram_depth = 64,
		ram_block1a_4.port_a_logical_ram_width = 32,
		ram_block1a_4.port_a_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_4.port_b_address_clock = "clock0",
		ram_block1a_4.port_b_address_width = 6,
		ram_block1a_4.port_b_data_in_clock = "clock0",
		ram_block1a_4.port_b_data_out_clear = "none",
		ram_block1a_4.port_b_data_width = 1,
		ram_block1a_4.port_b_first_address = 0,
		ram_block1a_4.port_b_first_bit_number = 4,
		ram_block1a_4.port_b_last_address = 63,
		ram_block1a_4.port_b_logical_ram_depth = 64,
		ram_block1a_4.port_b_logical_ram_width = 32,
		ram_block1a_4.port_b_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_4.port_b_read_enable_clock = "clock0",
		ram_block1a_4.port_b_write_enable_clock = "clock0",
		ram_block1a_4.power_up_uninitialized = "false",
		ram_block1a_4.ram_block_type = "AUTO",
		ram_block1a_4.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_5
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[5:0]}),
	.portadatain({data_a[5]}),
	.portadataout(wire_ram_block1a_5portadataout[0:0]),
	.portare(1'b1),
	.portawe(wren_a),
	.portbaddr({address_b_wire[5:0]}),
	.portbdatain({data_b[5]}),
	.portbdataout(wire_ram_block1a_5portbdataout[0:0]),
	.portbre(1'b1),
	.portbwe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_5.clk0_core_clock_enable = "none",
		ram_block1a_5.clk0_input_clock_enable = "none",
		ram_block1a_5.connectivity_checking = "OFF",
		ram_block1a_5.init_file = "../bootrom.hex",
		ram_block1a_5.init_file_layout = "port_a",
		ram_block1a_5.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_5.mem_init0 = 64'h0000018143081148,
		ram_block1a_5.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_5.operation_mode = "bidir_dual_port",
		ram_block1a_5.port_a_address_width = 6,
		ram_block1a_5.port_a_data_out_clear = "none",
		ram_block1a_5.port_a_data_width = 1,
		ram_block1a_5.port_a_first_address = 0,
		ram_block1a_5.port_a_first_bit_number = 5,
		ram_block1a_5.port_a_last_address = 63,
		ram_block1a_5.port_a_logical_ram_depth = 64,
		ram_block1a_5.port_a_logical_ram_width = 32,
		ram_block1a_5.port_a_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_5.port_b_address_clock = "clock0",
		ram_block1a_5.port_b_address_width = 6,
		ram_block1a_5.port_b_data_in_clock = "clock0",
		ram_block1a_5.port_b_data_out_clear = "none",
		ram_block1a_5.port_b_data_width = 1,
		ram_block1a_5.port_b_first_address = 0,
		ram_block1a_5.port_b_first_bit_number = 5,
		ram_block1a_5.port_b_last_address = 63,
		ram_block1a_5.port_b_logical_ram_depth = 64,
		ram_block1a_5.port_b_logical_ram_width = 32,
		ram_block1a_5.port_b_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_5.port_b_read_enable_clock = "clock0",
		ram_block1a_5.port_b_write_enable_clock = "clock0",
		ram_block1a_5.power_up_uninitialized = "false",
		ram_block1a_5.ram_block_type = "AUTO",
		ram_block1a_5.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_6
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[5:0]}),
	.portadatain({data_a[6]}),
	.portadataout(wire_ram_block1a_6portadataout[0:0]),
	.portare(1'b1),
	.portawe(wren_a),
	.portbaddr({address_b_wire[5:0]}),
	.portbdatain({data_b[6]}),
	.portbdataout(wire_ram_block1a_6portbdataout[0:0]),
	.portbre(1'b1),
	.portbwe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_6.clk0_core_clock_enable = "none",
		ram_block1a_6.clk0_input_clock_enable = "none",
		ram_block1a_6.connectivity_checking = "OFF",
		ram_block1a_6.init_file = "../bootrom.hex",
		ram_block1a_6.init_file_layout = "port_a",
		ram_block1a_6.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_6.mem_init0 = 64'h0000008042A8136B,
		ram_block1a_6.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_6.operation_mode = "bidir_dual_port",
		ram_block1a_6.port_a_address_width = 6,
		ram_block1a_6.port_a_data_out_clear = "none",
		ram_block1a_6.port_a_data_width = 1,
		ram_block1a_6.port_a_first_address = 0,
		ram_block1a_6.port_a_first_bit_number = 6,
		ram_block1a_6.port_a_last_address = 63,
		ram_block1a_6.port_a_logical_ram_depth = 64,
		ram_block1a_6.port_a_logical_ram_width = 32,
		ram_block1a_6.port_a_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_6.port_b_address_clock = "clock0",
		ram_block1a_6.port_b_address_width = 6,
		ram_block1a_6.port_b_data_in_clock = "clock0",
		ram_block1a_6.port_b_data_out_clear = "none",
		ram_block1a_6.port_b_data_width = 1,
		ram_block1a_6.port_b_first_address = 0,
		ram_block1a_6.port_b_first_bit_number = 6,
		ram_block1a_6.port_b_last_address = 63,
		ram_block1a_6.port_b_logical_ram_depth = 64,
		ram_block1a_6.port_b_logical_ram_width = 32,
		ram_block1a_6.port_b_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_6.port_b_read_enable_clock = "clock0",
		ram_block1a_6.port_b_write_enable_clock = "clock0",
		ram_block1a_6.power_up_uninitialized = "false",
		ram_block1a_6.ram_block_type = "AUTO",
		ram_block1a_6.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_7
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[5:0]}),
	.portadatain({data_a[7]}),
	.portadataout(wire_ram_block1a_7portadataout[0:0]),
	.portare(1'b1),
	.portawe(wren_a),
	.portbaddr({address_b_wire[5:0]}),
	.portbdatain({data_b[7]}),
	.portbdataout(wire_ram_block1a_7portbdataout[0:0]),
	.portbre(1'b1),
	.portbwe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_7.clk0_core_clock_enable = "none",
		ram_block1a_7.clk0_input_clock_enable = "none",
		ram_block1a_7.connectivity_checking = "OFF",
		ram_block1a_7.init_file = "../bootrom.hex",
		ram_block1a_7.init_file_layout = "port_a",
		ram_block1a_7.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_7.mem_init0 = 64'h0000008040CA1009,
		ram_block1a_7.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_7.operation_mode = "bidir_dual_port",
		ram_block1a_7.port_a_address_width = 6,
		ram_block1a_7.port_a_data_out_clear = "none",
		ram_block1a_7.port_a_data_width = 1,
		ram_block1a_7.port_a_first_address = 0,
		ram_block1a_7.port_a_first_bit_number = 7,
		ram_block1a_7.port_a_last_address = 63,
		ram_block1a_7.port_a_logical_ram_depth = 64,
		ram_block1a_7.port_a_logical_ram_width = 32,
		ram_block1a_7.port_a_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_7.port_b_address_clock = "clock0",
		ram_block1a_7.port_b_address_width = 6,
		ram_block1a_7.port_b_data_in_clock = "clock0",
		ram_block1a_7.port_b_data_out_clear = "none",
		ram_block1a_7.port_b_data_width = 1,
		ram_block1a_7.port_b_first_address = 0,
		ram_block1a_7.port_b_first_bit_number = 7,
		ram_block1a_7.port_b_last_address = 63,
		ram_block1a_7.port_b_logical_ram_depth = 64,
		ram_block1a_7.port_b_logical_ram_width = 32,
		ram_block1a_7.port_b_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_7.port_b_read_enable_clock = "clock0",
		ram_block1a_7.port_b_write_enable_clock = "clock0",
		ram_block1a_7.power_up_uninitialized = "false",
		ram_block1a_7.ram_block_type = "AUTO",
		ram_block1a_7.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_8
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[5:0]}),
	.portadatain({data_a[8]}),
	.portadataout(wire_ram_block1a_8portadataout[0:0]),
	.portare(1'b1),
	.portawe(wren_a),
	.portbaddr({address_b_wire[5:0]}),
	.portbdatain({data_b[8]}),
	.portbdataout(wire_ram_block1a_8portbdataout[0:0]),
	.portbre(1'b1),
	.portbwe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_8.clk0_core_clock_enable = "none",
		ram_block1a_8.clk0_input_clock_enable = "none",
		ram_block1a_8.connectivity_checking = "OFF",
		ram_block1a_8.init_file = "../bootrom.hex",
		ram_block1a_8.init_file_layout = "port_a",
		ram_block1a_8.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_8.mem_init0 = 64'h0000008043081148,
		ram_block1a_8.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_8.operation_mode = "bidir_dual_port",
		ram_block1a_8.port_a_address_width = 6,
		ram_block1a_8.port_a_data_out_clear = "none",
		ram_block1a_8.port_a_data_width = 1,
		ram_block1a_8.port_a_first_address = 0,
		ram_block1a_8.port_a_first_bit_number = 8,
		ram_block1a_8.port_a_last_address = 63,
		ram_block1a_8.port_a_logical_ram_depth = 64,
		ram_block1a_8.port_a_logical_ram_width = 32,
		ram_block1a_8.port_a_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_8.port_b_address_clock = "clock0",
		ram_block1a_8.port_b_address_width = 6,
		ram_block1a_8.port_b_data_in_clock = "clock0",
		ram_block1a_8.port_b_data_out_clear = "none",
		ram_block1a_8.port_b_data_width = 1,
		ram_block1a_8.port_b_first_address = 0,
		ram_block1a_8.port_b_first_bit_number = 8,
		ram_block1a_8.port_b_last_address = 63,
		ram_block1a_8.port_b_logical_ram_depth = 64,
		ram_block1a_8.port_b_logical_ram_width = 32,
		ram_block1a_8.port_b_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_8.port_b_read_enable_clock = "clock0",
		ram_block1a_8.port_b_write_enable_clock = "clock0",
		ram_block1a_8.power_up_uninitialized = "false",
		ram_block1a_8.ram_block_type = "AUTO",
		ram_block1a_8.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_9
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[5:0]}),
	.portadatain({data_a[9]}),
	.portadataout(wire_ram_block1a_9portadataout[0:0]),
	.portare(1'b1),
	.portawe(wren_a),
	.portbaddr({address_b_wire[5:0]}),
	.portbdatain({data_b[9]}),
	.portbdataout(wire_ram_block1a_9portbdataout[0:0]),
	.portbre(1'b1),
	.portbwe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_9.clk0_core_clock_enable = "none",
		ram_block1a_9.clk0_input_clock_enable = "none",
		ram_block1a_9.connectivity_checking = "OFF",
		ram_block1a_9.init_file = "../bootrom.hex",
		ram_block1a_9.init_file_layout = "port_a",
		ram_block1a_9.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_9.mem_init0 = 64'h0000009ACBF9312A,
		ram_block1a_9.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_9.operation_mode = "bidir_dual_port",
		ram_block1a_9.port_a_address_width = 6,
		ram_block1a_9.port_a_data_out_clear = "none",
		ram_block1a_9.port_a_data_width = 1,
		ram_block1a_9.port_a_first_address = 0,
		ram_block1a_9.port_a_first_bit_number = 9,
		ram_block1a_9.port_a_last_address = 63,
		ram_block1a_9.port_a_logical_ram_depth = 64,
		ram_block1a_9.port_a_logical_ram_width = 32,
		ram_block1a_9.port_a_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_9.port_b_address_clock = "clock0",
		ram_block1a_9.port_b_address_width = 6,
		ram_block1a_9.port_b_data_in_clock = "clock0",
		ram_block1a_9.port_b_data_out_clear = "none",
		ram_block1a_9.port_b_data_width = 1,
		ram_block1a_9.port_b_first_address = 0,
		ram_block1a_9.port_b_first_bit_number = 9,
		ram_block1a_9.port_b_last_address = 63,
		ram_block1a_9.port_b_logical_ram_depth = 64,
		ram_block1a_9.port_b_logical_ram_width = 32,
		ram_block1a_9.port_b_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_9.port_b_read_enable_clock = "clock0",
		ram_block1a_9.port_b_write_enable_clock = "clock0",
		ram_block1a_9.power_up_uninitialized = "false",
		ram_block1a_9.ram_block_type = "AUTO",
		ram_block1a_9.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_10
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[5:0]}),
	.portadatain({data_a[10]}),
	.portadataout(wire_ram_block1a_10portadataout[0:0]),
	.portare(1'b1),
	.portawe(wren_a),
	.portbaddr({address_b_wire[5:0]}),
	.portbdatain({data_b[10]}),
	.portbdataout(wire_ram_block1a_10portbdataout[0:0]),
	.portbre(1'b1),
	.portbwe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_10.clk0_core_clock_enable = "none",
		ram_block1a_10.clk0_input_clock_enable = "none",
		ram_block1a_10.connectivity_checking = "OFF",
		ram_block1a_10.init_file = "../bootrom.hex",
		ram_block1a_10.init_file_layout = "port_a",
		ram_block1a_10.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_10.mem_init0 = 64'h000000E4400A1208,
		ram_block1a_10.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_10.operation_mode = "bidir_dual_port",
		ram_block1a_10.port_a_address_width = 6,
		ram_block1a_10.port_a_data_out_clear = "none",
		ram_block1a_10.port_a_data_width = 1,
		ram_block1a_10.port_a_first_address = 0,
		ram_block1a_10.port_a_first_bit_number = 10,
		ram_block1a_10.port_a_last_address = 63,
		ram_block1a_10.port_a_logical_ram_depth = 64,
		ram_block1a_10.port_a_logical_ram_width = 32,
		ram_block1a_10.port_a_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_10.port_b_address_clock = "clock0",
		ram_block1a_10.port_b_address_width = 6,
		ram_block1a_10.port_b_data_in_clock = "clock0",
		ram_block1a_10.port_b_data_out_clear = "none",
		ram_block1a_10.port_b_data_width = 1,
		ram_block1a_10.port_b_first_address = 0,
		ram_block1a_10.port_b_first_bit_number = 10,
		ram_block1a_10.port_b_last_address = 63,
		ram_block1a_10.port_b_logical_ram_depth = 64,
		ram_block1a_10.port_b_logical_ram_width = 32,
		ram_block1a_10.port_b_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_10.port_b_read_enable_clock = "clock0",
		ram_block1a_10.port_b_write_enable_clock = "clock0",
		ram_block1a_10.power_up_uninitialized = "false",
		ram_block1a_10.ram_block_type = "AUTO",
		ram_block1a_10.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_11
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[5:0]}),
	.portadatain({data_a[11]}),
	.portadataout(wire_ram_block1a_11portadataout[0:0]),
	.portare(1'b1),
	.portawe(wren_a),
	.portbaddr({address_b_wire[5:0]}),
	.portbdatain({data_b[11]}),
	.portbdataout(wire_ram_block1a_11portbdataout[0:0]),
	.portbre(1'b1),
	.portbwe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_11.clk0_core_clock_enable = "none",
		ram_block1a_11.clk0_input_clock_enable = "none",
		ram_block1a_11.connectivity_checking = "OFF",
		ram_block1a_11.init_file = "../bootrom.hex",
		ram_block1a_11.init_file_layout = "port_a",
		ram_block1a_11.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_11.mem_init0 = 64'h0000008070081008,
		ram_block1a_11.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_11.operation_mode = "bidir_dual_port",
		ram_block1a_11.port_a_address_width = 6,
		ram_block1a_11.port_a_data_out_clear = "none",
		ram_block1a_11.port_a_data_width = 1,
		ram_block1a_11.port_a_first_address = 0,
		ram_block1a_11.port_a_first_bit_number = 11,
		ram_block1a_11.port_a_last_address = 63,
		ram_block1a_11.port_a_logical_ram_depth = 64,
		ram_block1a_11.port_a_logical_ram_width = 32,
		ram_block1a_11.port_a_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_11.port_b_address_clock = "clock0",
		ram_block1a_11.port_b_address_width = 6,
		ram_block1a_11.port_b_data_in_clock = "clock0",
		ram_block1a_11.port_b_data_out_clear = "none",
		ram_block1a_11.port_b_data_width = 1,
		ram_block1a_11.port_b_first_address = 0,
		ram_block1a_11.port_b_first_bit_number = 11,
		ram_block1a_11.port_b_last_address = 63,
		ram_block1a_11.port_b_logical_ram_depth = 64,
		ram_block1a_11.port_b_logical_ram_width = 32,
		ram_block1a_11.port_b_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_11.port_b_read_enable_clock = "clock0",
		ram_block1a_11.port_b_write_enable_clock = "clock0",
		ram_block1a_11.power_up_uninitialized = "false",
		ram_block1a_11.ram_block_type = "AUTO",
		ram_block1a_11.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_12
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[5:0]}),
	.portadatain({data_a[12]}),
	.portadataout(wire_ram_block1a_12portadataout[0:0]),
	.portare(1'b1),
	.portawe(wren_a),
	.portbaddr({address_b_wire[5:0]}),
	.portbdatain({data_b[12]}),
	.portbdataout(wire_ram_block1a_12portbdataout[0:0]),
	.portbre(1'b1),
	.portbwe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_12.clk0_core_clock_enable = "none",
		ram_block1a_12.clk0_input_clock_enable = "none",
		ram_block1a_12.connectivity_checking = "OFF",
		ram_block1a_12.init_file = "../bootrom.hex",
		ram_block1a_12.init_file_layout = "port_a",
		ram_block1a_12.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_12.mem_init0 = 64'h0000009048081808,
		ram_block1a_12.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_12.operation_mode = "bidir_dual_port",
		ram_block1a_12.port_a_address_width = 6,
		ram_block1a_12.port_a_data_out_clear = "none",
		ram_block1a_12.port_a_data_width = 1,
		ram_block1a_12.port_a_first_address = 0,
		ram_block1a_12.port_a_first_bit_number = 12,
		ram_block1a_12.port_a_last_address = 63,
		ram_block1a_12.port_a_logical_ram_depth = 64,
		ram_block1a_12.port_a_logical_ram_width = 32,
		ram_block1a_12.port_a_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_12.port_b_address_clock = "clock0",
		ram_block1a_12.port_b_address_width = 6,
		ram_block1a_12.port_b_data_in_clock = "clock0",
		ram_block1a_12.port_b_data_out_clear = "none",
		ram_block1a_12.port_b_data_width = 1,
		ram_block1a_12.port_b_first_address = 0,
		ram_block1a_12.port_b_first_bit_number = 12,
		ram_block1a_12.port_b_last_address = 63,
		ram_block1a_12.port_b_logical_ram_depth = 64,
		ram_block1a_12.port_b_logical_ram_width = 32,
		ram_block1a_12.port_b_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_12.port_b_read_enable_clock = "clock0",
		ram_block1a_12.port_b_write_enable_clock = "clock0",
		ram_block1a_12.power_up_uninitialized = "false",
		ram_block1a_12.ram_block_type = "AUTO",
		ram_block1a_12.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_13
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[5:0]}),
	.portadatain({data_a[13]}),
	.portadataout(wire_ram_block1a_13portadataout[0:0]),
	.portare(1'b1),
	.portawe(wren_a),
	.portbaddr({address_b_wire[5:0]}),
	.portbdatain({data_b[13]}),
	.portbdataout(wire_ram_block1a_13portbdataout[0:0]),
	.portbre(1'b1),
	.portbwe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_13.clk0_core_clock_enable = "none",
		ram_block1a_13.clk0_input_clock_enable = "none",
		ram_block1a_13.connectivity_checking = "OFF",
		ram_block1a_13.init_file = "../bootrom.hex",
		ram_block1a_13.init_file_layout = "port_a",
		ram_block1a_13.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_13.mem_init0 = 64'h0000008040081048,
		ram_block1a_13.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_13.operation_mode = "bidir_dual_port",
		ram_block1a_13.port_a_address_width = 6,
		ram_block1a_13.port_a_data_out_clear = "none",
		ram_block1a_13.port_a_data_width = 1,
		ram_block1a_13.port_a_first_address = 0,
		ram_block1a_13.port_a_first_bit_number = 13,
		ram_block1a_13.port_a_last_address = 63,
		ram_block1a_13.port_a_logical_ram_depth = 64,
		ram_block1a_13.port_a_logical_ram_width = 32,
		ram_block1a_13.port_a_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_13.port_b_address_clock = "clock0",
		ram_block1a_13.port_b_address_width = 6,
		ram_block1a_13.port_b_data_in_clock = "clock0",
		ram_block1a_13.port_b_data_out_clear = "none",
		ram_block1a_13.port_b_data_width = 1,
		ram_block1a_13.port_b_first_address = 0,
		ram_block1a_13.port_b_first_bit_number = 13,
		ram_block1a_13.port_b_last_address = 63,
		ram_block1a_13.port_b_logical_ram_depth = 64,
		ram_block1a_13.port_b_logical_ram_width = 32,
		ram_block1a_13.port_b_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_13.port_b_read_enable_clock = "clock0",
		ram_block1a_13.port_b_write_enable_clock = "clock0",
		ram_block1a_13.power_up_uninitialized = "false",
		ram_block1a_13.ram_block_type = "AUTO",
		ram_block1a_13.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_14
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[5:0]}),
	.portadatain({data_a[14]}),
	.portadataout(wire_ram_block1a_14portadataout[0:0]),
	.portare(1'b1),
	.portawe(wren_a),
	.portbaddr({address_b_wire[5:0]}),
	.portbdatain({data_b[14]}),
	.portbdataout(wire_ram_block1a_14portbdataout[0:0]),
	.portbre(1'b1),
	.portbwe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_14.clk0_core_clock_enable = "none",
		ram_block1a_14.clk0_input_clock_enable = "none",
		ram_block1a_14.connectivity_checking = "OFF",
		ram_block1a_14.init_file = "../bootrom.hex",
		ram_block1a_14.init_file_layout = "port_a",
		ram_block1a_14.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_14.mem_init0 = 64'h0000008040081008,
		ram_block1a_14.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_14.operation_mode = "bidir_dual_port",
		ram_block1a_14.port_a_address_width = 6,
		ram_block1a_14.port_a_data_out_clear = "none",
		ram_block1a_14.port_a_data_width = 1,
		ram_block1a_14.port_a_first_address = 0,
		ram_block1a_14.port_a_first_bit_number = 14,
		ram_block1a_14.port_a_last_address = 63,
		ram_block1a_14.port_a_logical_ram_depth = 64,
		ram_block1a_14.port_a_logical_ram_width = 32,
		ram_block1a_14.port_a_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_14.port_b_address_clock = "clock0",
		ram_block1a_14.port_b_address_width = 6,
		ram_block1a_14.port_b_data_in_clock = "clock0",
		ram_block1a_14.port_b_data_out_clear = "none",
		ram_block1a_14.port_b_data_width = 1,
		ram_block1a_14.port_b_first_address = 0,
		ram_block1a_14.port_b_first_bit_number = 14,
		ram_block1a_14.port_b_last_address = 63,
		ram_block1a_14.port_b_logical_ram_depth = 64,
		ram_block1a_14.port_b_logical_ram_width = 32,
		ram_block1a_14.port_b_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_14.port_b_read_enable_clock = "clock0",
		ram_block1a_14.port_b_write_enable_clock = "clock0",
		ram_block1a_14.power_up_uninitialized = "false",
		ram_block1a_14.ram_block_type = "AUTO",
		ram_block1a_14.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_15
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[5:0]}),
	.portadatain({data_a[15]}),
	.portadataout(wire_ram_block1a_15portadataout[0:0]),
	.portare(1'b1),
	.portawe(wren_a),
	.portbaddr({address_b_wire[5:0]}),
	.portbdatain({data_b[15]}),
	.portbdataout(wire_ram_block1a_15portbdataout[0:0]),
	.portbre(1'b1),
	.portbwe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_15.clk0_core_clock_enable = "none",
		ram_block1a_15.clk0_input_clock_enable = "none",
		ram_block1a_15.connectivity_checking = "OFF",
		ram_block1a_15.init_file = "../bootrom.hex",
		ram_block1a_15.init_file_layout = "port_a",
		ram_block1a_15.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_15.mem_init0 = 64'h0000008040081008,
		ram_block1a_15.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_15.operation_mode = "bidir_dual_port",
		ram_block1a_15.port_a_address_width = 6,
		ram_block1a_15.port_a_data_out_clear = "none",
		ram_block1a_15.port_a_data_width = 1,
		ram_block1a_15.port_a_first_address = 0,
		ram_block1a_15.port_a_first_bit_number = 15,
		ram_block1a_15.port_a_last_address = 63,
		ram_block1a_15.port_a_logical_ram_depth = 64,
		ram_block1a_15.port_a_logical_ram_width = 32,
		ram_block1a_15.port_a_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_15.port_b_address_clock = "clock0",
		ram_block1a_15.port_b_address_width = 6,
		ram_block1a_15.port_b_data_in_clock = "clock0",
		ram_block1a_15.port_b_data_out_clear = "none",
		ram_block1a_15.port_b_data_width = 1,
		ram_block1a_15.port_b_first_address = 0,
		ram_block1a_15.port_b_first_bit_number = 15,
		ram_block1a_15.port_b_last_address = 63,
		ram_block1a_15.port_b_logical_ram_depth = 64,
		ram_block1a_15.port_b_logical_ram_width = 32,
		ram_block1a_15.port_b_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_15.port_b_read_enable_clock = "clock0",
		ram_block1a_15.port_b_write_enable_clock = "clock0",
		ram_block1a_15.power_up_uninitialized = "false",
		ram_block1a_15.ram_block_type = "AUTO",
		ram_block1a_15.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_16
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[5:0]}),
	.portadatain({data_a[16]}),
	.portadataout(wire_ram_block1a_16portadataout[0:0]),
	.portare(1'b1),
	.portawe(wren_a),
	.portbaddr({address_b_wire[5:0]}),
	.portbdatain({data_b[16]}),
	.portbdataout(wire_ram_block1a_16portbdataout[0:0]),
	.portbre(1'b1),
	.portbwe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_16.clk0_core_clock_enable = "none",
		ram_block1a_16.clk0_input_clock_enable = "none",
		ram_block1a_16.connectivity_checking = "OFF",
		ram_block1a_16.init_file = "../bootrom.hex",
		ram_block1a_16.init_file_layout = "port_a",
		ram_block1a_16.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_16.mem_init0 = 64'h0000008440081008,
		ram_block1a_16.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_16.operation_mode = "bidir_dual_port",
		ram_block1a_16.port_a_address_width = 6,
		ram_block1a_16.port_a_data_out_clear = "none",
		ram_block1a_16.port_a_data_width = 1,
		ram_block1a_16.port_a_first_address = 0,
		ram_block1a_16.port_a_first_bit_number = 16,
		ram_block1a_16.port_a_last_address = 63,
		ram_block1a_16.port_a_logical_ram_depth = 64,
		ram_block1a_16.port_a_logical_ram_width = 32,
		ram_block1a_16.port_a_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_16.port_b_address_clock = "clock0",
		ram_block1a_16.port_b_address_width = 6,
		ram_block1a_16.port_b_data_in_clock = "clock0",
		ram_block1a_16.port_b_data_out_clear = "none",
		ram_block1a_16.port_b_data_width = 1,
		ram_block1a_16.port_b_first_address = 0,
		ram_block1a_16.port_b_first_bit_number = 16,
		ram_block1a_16.port_b_last_address = 63,
		ram_block1a_16.port_b_logical_ram_depth = 64,
		ram_block1a_16.port_b_logical_ram_width = 32,
		ram_block1a_16.port_b_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_16.port_b_read_enable_clock = "clock0",
		ram_block1a_16.port_b_write_enable_clock = "clock0",
		ram_block1a_16.power_up_uninitialized = "false",
		ram_block1a_16.ram_block_type = "AUTO",
		ram_block1a_16.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_17
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[5:0]}),
	.portadatain({data_a[17]}),
	.portadataout(wire_ram_block1a_17portadataout[0:0]),
	.portare(1'b1),
	.portawe(wren_a),
	.portbaddr({address_b_wire[5:0]}),
	.portbdatain({data_b[17]}),
	.portbdataout(wire_ram_block1a_17portbdataout[0:0]),
	.portbre(1'b1),
	.portbwe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_17.clk0_core_clock_enable = "none",
		ram_block1a_17.clk0_input_clock_enable = "none",
		ram_block1a_17.connectivity_checking = "OFF",
		ram_block1a_17.init_file = "../bootrom.hex",
		ram_block1a_17.init_file_layout = "port_a",
		ram_block1a_17.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_17.mem_init0 = 64'h0000008040081008,
		ram_block1a_17.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_17.operation_mode = "bidir_dual_port",
		ram_block1a_17.port_a_address_width = 6,
		ram_block1a_17.port_a_data_out_clear = "none",
		ram_block1a_17.port_a_data_width = 1,
		ram_block1a_17.port_a_first_address = 0,
		ram_block1a_17.port_a_first_bit_number = 17,
		ram_block1a_17.port_a_last_address = 63,
		ram_block1a_17.port_a_logical_ram_depth = 64,
		ram_block1a_17.port_a_logical_ram_width = 32,
		ram_block1a_17.port_a_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_17.port_b_address_clock = "clock0",
		ram_block1a_17.port_b_address_width = 6,
		ram_block1a_17.port_b_data_in_clock = "clock0",
		ram_block1a_17.port_b_data_out_clear = "none",
		ram_block1a_17.port_b_data_width = 1,
		ram_block1a_17.port_b_first_address = 0,
		ram_block1a_17.port_b_first_bit_number = 17,
		ram_block1a_17.port_b_last_address = 63,
		ram_block1a_17.port_b_logical_ram_depth = 64,
		ram_block1a_17.port_b_logical_ram_width = 32,
		ram_block1a_17.port_b_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_17.port_b_read_enable_clock = "clock0",
		ram_block1a_17.port_b_write_enable_clock = "clock0",
		ram_block1a_17.power_up_uninitialized = "false",
		ram_block1a_17.ram_block_type = "AUTO",
		ram_block1a_17.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_18
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[5:0]}),
	.portadatain({data_a[18]}),
	.portadataout(wire_ram_block1a_18portadataout[0:0]),
	.portare(1'b1),
	.portawe(wren_a),
	.portbaddr({address_b_wire[5:0]}),
	.portbdatain({data_b[18]}),
	.portbdataout(wire_ram_block1a_18portbdataout[0:0]),
	.portbre(1'b1),
	.portbwe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_18.clk0_core_clock_enable = "none",
		ram_block1a_18.clk0_input_clock_enable = "none",
		ram_block1a_18.connectivity_checking = "OFF",
		ram_block1a_18.init_file = "../bootrom.hex",
		ram_block1a_18.init_file_layout = "port_a",
		ram_block1a_18.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_18.mem_init0 = 64'h0000008040081008,
		ram_block1a_18.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_18.operation_mode = "bidir_dual_port",
		ram_block1a_18.port_a_address_width = 6,
		ram_block1a_18.port_a_data_out_clear = "none",
		ram_block1a_18.port_a_data_width = 1,
		ram_block1a_18.port_a_first_address = 0,
		ram_block1a_18.port_a_first_bit_number = 18,
		ram_block1a_18.port_a_last_address = 63,
		ram_block1a_18.port_a_logical_ram_depth = 64,
		ram_block1a_18.port_a_logical_ram_width = 32,
		ram_block1a_18.port_a_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_18.port_b_address_clock = "clock0",
		ram_block1a_18.port_b_address_width = 6,
		ram_block1a_18.port_b_data_in_clock = "clock0",
		ram_block1a_18.port_b_data_out_clear = "none",
		ram_block1a_18.port_b_data_width = 1,
		ram_block1a_18.port_b_first_address = 0,
		ram_block1a_18.port_b_first_bit_number = 18,
		ram_block1a_18.port_b_last_address = 63,
		ram_block1a_18.port_b_logical_ram_depth = 64,
		ram_block1a_18.port_b_logical_ram_width = 32,
		ram_block1a_18.port_b_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_18.port_b_read_enable_clock = "clock0",
		ram_block1a_18.port_b_write_enable_clock = "clock0",
		ram_block1a_18.power_up_uninitialized = "false",
		ram_block1a_18.ram_block_type = "AUTO",
		ram_block1a_18.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_19
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[5:0]}),
	.portadatain({data_a[19]}),
	.portadataout(wire_ram_block1a_19portadataout[0:0]),
	.portare(1'b1),
	.portawe(wren_a),
	.portbaddr({address_b_wire[5:0]}),
	.portbdatain({data_b[19]}),
	.portbdataout(wire_ram_block1a_19portbdataout[0:0]),
	.portbre(1'b1),
	.portbwe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_19.clk0_core_clock_enable = "none",
		ram_block1a_19.clk0_input_clock_enable = "none",
		ram_block1a_19.connectivity_checking = "OFF",
		ram_block1a_19.init_file = "../bootrom.hex",
		ram_block1a_19.init_file_layout = "port_a",
		ram_block1a_19.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_19.mem_init0 = 64'h0000008040081008,
		ram_block1a_19.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_19.operation_mode = "bidir_dual_port",
		ram_block1a_19.port_a_address_width = 6,
		ram_block1a_19.port_a_data_out_clear = "none",
		ram_block1a_19.port_a_data_width = 1,
		ram_block1a_19.port_a_first_address = 0,
		ram_block1a_19.port_a_first_bit_number = 19,
		ram_block1a_19.port_a_last_address = 63,
		ram_block1a_19.port_a_logical_ram_depth = 64,
		ram_block1a_19.port_a_logical_ram_width = 32,
		ram_block1a_19.port_a_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_19.port_b_address_clock = "clock0",
		ram_block1a_19.port_b_address_width = 6,
		ram_block1a_19.port_b_data_in_clock = "clock0",
		ram_block1a_19.port_b_data_out_clear = "none",
		ram_block1a_19.port_b_data_width = 1,
		ram_block1a_19.port_b_first_address = 0,
		ram_block1a_19.port_b_first_bit_number = 19,
		ram_block1a_19.port_b_last_address = 63,
		ram_block1a_19.port_b_logical_ram_depth = 64,
		ram_block1a_19.port_b_logical_ram_width = 32,
		ram_block1a_19.port_b_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_19.port_b_read_enable_clock = "clock0",
		ram_block1a_19.port_b_write_enable_clock = "clock0",
		ram_block1a_19.power_up_uninitialized = "false",
		ram_block1a_19.ram_block_type = "AUTO",
		ram_block1a_19.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_20
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[5:0]}),
	.portadatain({data_a[20]}),
	.portadataout(wire_ram_block1a_20portadataout[0:0]),
	.portare(1'b1),
	.portawe(wren_a),
	.portbaddr({address_b_wire[5:0]}),
	.portbdatain({data_b[20]}),
	.portbdataout(wire_ram_block1a_20portbdataout[0:0]),
	.portbre(1'b1),
	.portbwe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_20.clk0_core_clock_enable = "none",
		ram_block1a_20.clk0_input_clock_enable = "none",
		ram_block1a_20.connectivity_checking = "OFF",
		ram_block1a_20.init_file = "../bootrom.hex",
		ram_block1a_20.init_file_layout = "port_a",
		ram_block1a_20.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_20.mem_init0 = 64'h0000008040081008,
		ram_block1a_20.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_20.operation_mode = "bidir_dual_port",
		ram_block1a_20.port_a_address_width = 6,
		ram_block1a_20.port_a_data_out_clear = "none",
		ram_block1a_20.port_a_data_width = 1,
		ram_block1a_20.port_a_first_address = 0,
		ram_block1a_20.port_a_first_bit_number = 20,
		ram_block1a_20.port_a_last_address = 63,
		ram_block1a_20.port_a_logical_ram_depth = 64,
		ram_block1a_20.port_a_logical_ram_width = 32,
		ram_block1a_20.port_a_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_20.port_b_address_clock = "clock0",
		ram_block1a_20.port_b_address_width = 6,
		ram_block1a_20.port_b_data_in_clock = "clock0",
		ram_block1a_20.port_b_data_out_clear = "none",
		ram_block1a_20.port_b_data_width = 1,
		ram_block1a_20.port_b_first_address = 0,
		ram_block1a_20.port_b_first_bit_number = 20,
		ram_block1a_20.port_b_last_address = 63,
		ram_block1a_20.port_b_logical_ram_depth = 64,
		ram_block1a_20.port_b_logical_ram_width = 32,
		ram_block1a_20.port_b_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_20.port_b_read_enable_clock = "clock0",
		ram_block1a_20.port_b_write_enable_clock = "clock0",
		ram_block1a_20.power_up_uninitialized = "false",
		ram_block1a_20.ram_block_type = "AUTO",
		ram_block1a_20.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_21
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[5:0]}),
	.portadatain({data_a[21]}),
	.portadataout(wire_ram_block1a_21portadataout[0:0]),
	.portare(1'b1),
	.portawe(wren_a),
	.portbaddr({address_b_wire[5:0]}),
	.portbdatain({data_b[21]}),
	.portbdataout(wire_ram_block1a_21portbdataout[0:0]),
	.portbre(1'b1),
	.portbwe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_21.clk0_core_clock_enable = "none",
		ram_block1a_21.clk0_input_clock_enable = "none",
		ram_block1a_21.connectivity_checking = "OFF",
		ram_block1a_21.init_file = "../bootrom.hex",
		ram_block1a_21.init_file_layout = "port_a",
		ram_block1a_21.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_21.mem_init0 = 64'h0000008040081008,
		ram_block1a_21.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_21.operation_mode = "bidir_dual_port",
		ram_block1a_21.port_a_address_width = 6,
		ram_block1a_21.port_a_data_out_clear = "none",
		ram_block1a_21.port_a_data_width = 1,
		ram_block1a_21.port_a_first_address = 0,
		ram_block1a_21.port_a_first_bit_number = 21,
		ram_block1a_21.port_a_last_address = 63,
		ram_block1a_21.port_a_logical_ram_depth = 64,
		ram_block1a_21.port_a_logical_ram_width = 32,
		ram_block1a_21.port_a_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_21.port_b_address_clock = "clock0",
		ram_block1a_21.port_b_address_width = 6,
		ram_block1a_21.port_b_data_in_clock = "clock0",
		ram_block1a_21.port_b_data_out_clear = "none",
		ram_block1a_21.port_b_data_width = 1,
		ram_block1a_21.port_b_first_address = 0,
		ram_block1a_21.port_b_first_bit_number = 21,
		ram_block1a_21.port_b_last_address = 63,
		ram_block1a_21.port_b_logical_ram_depth = 64,
		ram_block1a_21.port_b_logical_ram_width = 32,
		ram_block1a_21.port_b_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_21.port_b_read_enable_clock = "clock0",
		ram_block1a_21.port_b_write_enable_clock = "clock0",
		ram_block1a_21.power_up_uninitialized = "false",
		ram_block1a_21.ram_block_type = "AUTO",
		ram_block1a_21.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_22
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[5:0]}),
	.portadatain({data_a[22]}),
	.portadataout(wire_ram_block1a_22portadataout[0:0]),
	.portare(1'b1),
	.portawe(wren_a),
	.portbaddr({address_b_wire[5:0]}),
	.portbdatain({data_b[22]}),
	.portbdataout(wire_ram_block1a_22portbdataout[0:0]),
	.portbre(1'b1),
	.portbwe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_22.clk0_core_clock_enable = "none",
		ram_block1a_22.clk0_input_clock_enable = "none",
		ram_block1a_22.connectivity_checking = "OFF",
		ram_block1a_22.init_file = "../bootrom.hex",
		ram_block1a_22.init_file_layout = "port_a",
		ram_block1a_22.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_22.mem_init0 = 64'h000000804008100A,
		ram_block1a_22.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_22.operation_mode = "bidir_dual_port",
		ram_block1a_22.port_a_address_width = 6,
		ram_block1a_22.port_a_data_out_clear = "none",
		ram_block1a_22.port_a_data_width = 1,
		ram_block1a_22.port_a_first_address = 0,
		ram_block1a_22.port_a_first_bit_number = 22,
		ram_block1a_22.port_a_last_address = 63,
		ram_block1a_22.port_a_logical_ram_depth = 64,
		ram_block1a_22.port_a_logical_ram_width = 32,
		ram_block1a_22.port_a_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_22.port_b_address_clock = "clock0",
		ram_block1a_22.port_b_address_width = 6,
		ram_block1a_22.port_b_data_in_clock = "clock0",
		ram_block1a_22.port_b_data_out_clear = "none",
		ram_block1a_22.port_b_data_width = 1,
		ram_block1a_22.port_b_first_address = 0,
		ram_block1a_22.port_b_first_bit_number = 22,
		ram_block1a_22.port_b_last_address = 63,
		ram_block1a_22.port_b_logical_ram_depth = 64,
		ram_block1a_22.port_b_logical_ram_width = 32,
		ram_block1a_22.port_b_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_22.port_b_read_enable_clock = "clock0",
		ram_block1a_22.port_b_write_enable_clock = "clock0",
		ram_block1a_22.power_up_uninitialized = "false",
		ram_block1a_22.ram_block_type = "AUTO",
		ram_block1a_22.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_23
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[5:0]}),
	.portadatain({data_a[23]}),
	.portadataout(wire_ram_block1a_23portadataout[0:0]),
	.portare(1'b1),
	.portawe(wren_a),
	.portbaddr({address_b_wire[5:0]}),
	.portbdatain({data_b[23]}),
	.portbdataout(wire_ram_block1a_23portbdataout[0:0]),
	.portbre(1'b1),
	.portbwe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_23.clk0_core_clock_enable = "none",
		ram_block1a_23.clk0_input_clock_enable = "none",
		ram_block1a_23.connectivity_checking = "OFF",
		ram_block1a_23.init_file = "../bootrom.hex",
		ram_block1a_23.init_file_layout = "port_a",
		ram_block1a_23.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_23.mem_init0 = 64'h0000008040081008,
		ram_block1a_23.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_23.operation_mode = "bidir_dual_port",
		ram_block1a_23.port_a_address_width = 6,
		ram_block1a_23.port_a_data_out_clear = "none",
		ram_block1a_23.port_a_data_width = 1,
		ram_block1a_23.port_a_first_address = 0,
		ram_block1a_23.port_a_first_bit_number = 23,
		ram_block1a_23.port_a_last_address = 63,
		ram_block1a_23.port_a_logical_ram_depth = 64,
		ram_block1a_23.port_a_logical_ram_width = 32,
		ram_block1a_23.port_a_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_23.port_b_address_clock = "clock0",
		ram_block1a_23.port_b_address_width = 6,
		ram_block1a_23.port_b_data_in_clock = "clock0",
		ram_block1a_23.port_b_data_out_clear = "none",
		ram_block1a_23.port_b_data_width = 1,
		ram_block1a_23.port_b_first_address = 0,
		ram_block1a_23.port_b_first_bit_number = 23,
		ram_block1a_23.port_b_last_address = 63,
		ram_block1a_23.port_b_logical_ram_depth = 64,
		ram_block1a_23.port_b_logical_ram_width = 32,
		ram_block1a_23.port_b_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_23.port_b_read_enable_clock = "clock0",
		ram_block1a_23.port_b_write_enable_clock = "clock0",
		ram_block1a_23.power_up_uninitialized = "false",
		ram_block1a_23.ram_block_type = "AUTO",
		ram_block1a_23.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_24
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[5:0]}),
	.portadatain({data_a[24]}),
	.portadataout(wire_ram_block1a_24portadataout[0:0]),
	.portare(1'b1),
	.portawe(wren_a),
	.portbaddr({address_b_wire[5:0]}),
	.portbdatain({data_b[24]}),
	.portbdataout(wire_ram_block1a_24portbdataout[0:0]),
	.portbre(1'b1),
	.portbwe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_24.clk0_core_clock_enable = "none",
		ram_block1a_24.clk0_input_clock_enable = "none",
		ram_block1a_24.connectivity_checking = "OFF",
		ram_block1a_24.init_file = "../bootrom.hex",
		ram_block1a_24.init_file_layout = "port_a",
		ram_block1a_24.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_24.mem_init0 = 64'h0000000000000000,
		ram_block1a_24.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_24.operation_mode = "bidir_dual_port",
		ram_block1a_24.port_a_address_width = 6,
		ram_block1a_24.port_a_data_out_clear = "none",
		ram_block1a_24.port_a_data_width = 1,
		ram_block1a_24.port_a_first_address = 0,
		ram_block1a_24.port_a_first_bit_number = 24,
		ram_block1a_24.port_a_last_address = 63,
		ram_block1a_24.port_a_logical_ram_depth = 64,
		ram_block1a_24.port_a_logical_ram_width = 32,
		ram_block1a_24.port_a_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_24.port_b_address_clock = "clock0",
		ram_block1a_24.port_b_address_width = 6,
		ram_block1a_24.port_b_data_in_clock = "clock0",
		ram_block1a_24.port_b_data_out_clear = "none",
		ram_block1a_24.port_b_data_width = 1,
		ram_block1a_24.port_b_first_address = 0,
		ram_block1a_24.port_b_first_bit_number = 24,
		ram_block1a_24.port_b_last_address = 63,
		ram_block1a_24.port_b_logical_ram_depth = 64,
		ram_block1a_24.port_b_logical_ram_width = 32,
		ram_block1a_24.port_b_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_24.port_b_read_enable_clock = "clock0",
		ram_block1a_24.port_b_write_enable_clock = "clock0",
		ram_block1a_24.power_up_uninitialized = "false",
		ram_block1a_24.ram_block_type = "AUTO",
		ram_block1a_24.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_25
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[5:0]}),
	.portadatain({data_a[25]}),
	.portadataout(wire_ram_block1a_25portadataout[0:0]),
	.portare(1'b1),
	.portawe(wren_a),
	.portbaddr({address_b_wire[5:0]}),
	.portbdatain({data_b[25]}),
	.portbdataout(wire_ram_block1a_25portbdataout[0:0]),
	.portbre(1'b1),
	.portbwe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_25.clk0_core_clock_enable = "none",
		ram_block1a_25.clk0_input_clock_enable = "none",
		ram_block1a_25.connectivity_checking = "OFF",
		ram_block1a_25.init_file = "../bootrom.hex",
		ram_block1a_25.init_file_layout = "port_a",
		ram_block1a_25.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_25.mem_init0 = 64'h0000010104000001,
		ram_block1a_25.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_25.operation_mode = "bidir_dual_port",
		ram_block1a_25.port_a_address_width = 6,
		ram_block1a_25.port_a_data_out_clear = "none",
		ram_block1a_25.port_a_data_width = 1,
		ram_block1a_25.port_a_first_address = 0,
		ram_block1a_25.port_a_first_bit_number = 25,
		ram_block1a_25.port_a_last_address = 63,
		ram_block1a_25.port_a_logical_ram_depth = 64,
		ram_block1a_25.port_a_logical_ram_width = 32,
		ram_block1a_25.port_a_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_25.port_b_address_clock = "clock0",
		ram_block1a_25.port_b_address_width = 6,
		ram_block1a_25.port_b_data_in_clock = "clock0",
		ram_block1a_25.port_b_data_out_clear = "none",
		ram_block1a_25.port_b_data_width = 1,
		ram_block1a_25.port_b_first_address = 0,
		ram_block1a_25.port_b_first_bit_number = 25,
		ram_block1a_25.port_b_last_address = 63,
		ram_block1a_25.port_b_logical_ram_depth = 64,
		ram_block1a_25.port_b_logical_ram_width = 32,
		ram_block1a_25.port_b_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_25.port_b_read_enable_clock = "clock0",
		ram_block1a_25.port_b_write_enable_clock = "clock0",
		ram_block1a_25.power_up_uninitialized = "false",
		ram_block1a_25.ram_block_type = "AUTO",
		ram_block1a_25.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_26
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[5:0]}),
	.portadatain({data_a[26]}),
	.portadataout(wire_ram_block1a_26portadataout[0:0]),
	.portare(1'b1),
	.portawe(wren_a),
	.portbaddr({address_b_wire[5:0]}),
	.portbdatain({data_b[26]}),
	.portbdataout(wire_ram_block1a_26portbdataout[0:0]),
	.portbre(1'b1),
	.portbwe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_26.clk0_core_clock_enable = "none",
		ram_block1a_26.clk0_input_clock_enable = "none",
		ram_block1a_26.connectivity_checking = "OFF",
		ram_block1a_26.init_file = "../bootrom.hex",
		ram_block1a_26.init_file_layout = "port_a",
		ram_block1a_26.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_26.mem_init0 = 64'h0000018343F01021,
		ram_block1a_26.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_26.operation_mode = "bidir_dual_port",
		ram_block1a_26.port_a_address_width = 6,
		ram_block1a_26.port_a_data_out_clear = "none",
		ram_block1a_26.port_a_data_width = 1,
		ram_block1a_26.port_a_first_address = 0,
		ram_block1a_26.port_a_first_bit_number = 26,
		ram_block1a_26.port_a_last_address = 63,
		ram_block1a_26.port_a_logical_ram_depth = 64,
		ram_block1a_26.port_a_logical_ram_width = 32,
		ram_block1a_26.port_a_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_26.port_b_address_clock = "clock0",
		ram_block1a_26.port_b_address_width = 6,
		ram_block1a_26.port_b_data_in_clock = "clock0",
		ram_block1a_26.port_b_data_out_clear = "none",
		ram_block1a_26.port_b_data_width = 1,
		ram_block1a_26.port_b_first_address = 0,
		ram_block1a_26.port_b_first_bit_number = 26,
		ram_block1a_26.port_b_last_address = 63,
		ram_block1a_26.port_b_logical_ram_depth = 64,
		ram_block1a_26.port_b_logical_ram_width = 32,
		ram_block1a_26.port_b_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_26.port_b_read_enable_clock = "clock0",
		ram_block1a_26.port_b_write_enable_clock = "clock0",
		ram_block1a_26.power_up_uninitialized = "false",
		ram_block1a_26.ram_block_type = "AUTO",
		ram_block1a_26.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_27
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[5:0]}),
	.portadatain({data_a[27]}),
	.portadataout(wire_ram_block1a_27portadataout[0:0]),
	.portare(1'b1),
	.portawe(wren_a),
	.portbaddr({address_b_wire[5:0]}),
	.portbdatain({data_b[27]}),
	.portbdataout(wire_ram_block1a_27portbdataout[0:0]),
	.portbre(1'b1),
	.portbwe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_27.clk0_core_clock_enable = "none",
		ram_block1a_27.clk0_input_clock_enable = "none",
		ram_block1a_27.connectivity_checking = "OFF",
		ram_block1a_27.init_file = "../bootrom.hex",
		ram_block1a_27.init_file_layout = "port_a",
		ram_block1a_27.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_27.mem_init0 = 64'h0000002613F14129,
		ram_block1a_27.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_27.operation_mode = "bidir_dual_port",
		ram_block1a_27.port_a_address_width = 6,
		ram_block1a_27.port_a_data_out_clear = "none",
		ram_block1a_27.port_a_data_width = 1,
		ram_block1a_27.port_a_first_address = 0,
		ram_block1a_27.port_a_first_bit_number = 27,
		ram_block1a_27.port_a_last_address = 63,
		ram_block1a_27.port_a_logical_ram_depth = 64,
		ram_block1a_27.port_a_logical_ram_width = 32,
		ram_block1a_27.port_a_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_27.port_b_address_clock = "clock0",
		ram_block1a_27.port_b_address_width = 6,
		ram_block1a_27.port_b_data_in_clock = "clock0",
		ram_block1a_27.port_b_data_out_clear = "none",
		ram_block1a_27.port_b_data_width = 1,
		ram_block1a_27.port_b_first_address = 0,
		ram_block1a_27.port_b_first_bit_number = 27,
		ram_block1a_27.port_b_last_address = 63,
		ram_block1a_27.port_b_logical_ram_depth = 64,
		ram_block1a_27.port_b_logical_ram_width = 32,
		ram_block1a_27.port_b_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_27.port_b_read_enable_clock = "clock0",
		ram_block1a_27.port_b_write_enable_clock = "clock0",
		ram_block1a_27.power_up_uninitialized = "false",
		ram_block1a_27.ram_block_type = "AUTO",
		ram_block1a_27.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_28
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[5:0]}),
	.portadatain({data_a[28]}),
	.portadataout(wire_ram_block1a_28portadataout[0:0]),
	.portare(1'b1),
	.portawe(wren_a),
	.portbaddr({address_b_wire[5:0]}),
	.portbdatain({data_b[28]}),
	.portbdataout(wire_ram_block1a_28portbdataout[0:0]),
	.portbre(1'b1),
	.portbwe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_28.clk0_core_clock_enable = "none",
		ram_block1a_28.clk0_input_clock_enable = "none",
		ram_block1a_28.connectivity_checking = "OFF",
		ram_block1a_28.init_file = "../bootrom.hex",
		ram_block1a_28.init_file_layout = "port_a",
		ram_block1a_28.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_28.mem_init0 = 64'h000000EA77F9786C,
		ram_block1a_28.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_28.operation_mode = "bidir_dual_port",
		ram_block1a_28.port_a_address_width = 6,
		ram_block1a_28.port_a_data_out_clear = "none",
		ram_block1a_28.port_a_data_width = 1,
		ram_block1a_28.port_a_first_address = 0,
		ram_block1a_28.port_a_first_bit_number = 28,
		ram_block1a_28.port_a_last_address = 63,
		ram_block1a_28.port_a_logical_ram_depth = 64,
		ram_block1a_28.port_a_logical_ram_width = 32,
		ram_block1a_28.port_a_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_28.port_b_address_clock = "clock0",
		ram_block1a_28.port_b_address_width = 6,
		ram_block1a_28.port_b_data_in_clock = "clock0",
		ram_block1a_28.port_b_data_out_clear = "none",
		ram_block1a_28.port_b_data_width = 1,
		ram_block1a_28.port_b_first_address = 0,
		ram_block1a_28.port_b_first_bit_number = 28,
		ram_block1a_28.port_b_last_address = 63,
		ram_block1a_28.port_b_logical_ram_depth = 64,
		ram_block1a_28.port_b_logical_ram_width = 32,
		ram_block1a_28.port_b_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_28.port_b_read_enable_clock = "clock0",
		ram_block1a_28.port_b_write_enable_clock = "clock0",
		ram_block1a_28.power_up_uninitialized = "false",
		ram_block1a_28.ram_block_type = "AUTO",
		ram_block1a_28.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_29
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[5:0]}),
	.portadatain({data_a[29]}),
	.portadataout(wire_ram_block1a_29portadataout[0:0]),
	.portare(1'b1),
	.portawe(wren_a),
	.portbaddr({address_b_wire[5:0]}),
	.portbdatain({data_b[29]}),
	.portbdataout(wire_ram_block1a_29portbdataout[0:0]),
	.portbre(1'b1),
	.portbwe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_29.clk0_core_clock_enable = "none",
		ram_block1a_29.clk0_input_clock_enable = "none",
		ram_block1a_29.connectivity_checking = "OFF",
		ram_block1a_29.init_file = "../bootrom.hex",
		ram_block1a_29.init_file_layout = "port_a",
		ram_block1a_29.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_29.mem_init0 = 64'h0000004420002905,
		ram_block1a_29.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_29.operation_mode = "bidir_dual_port",
		ram_block1a_29.port_a_address_width = 6,
		ram_block1a_29.port_a_data_out_clear = "none",
		ram_block1a_29.port_a_data_width = 1,
		ram_block1a_29.port_a_first_address = 0,
		ram_block1a_29.port_a_first_bit_number = 29,
		ram_block1a_29.port_a_last_address = 63,
		ram_block1a_29.port_a_logical_ram_depth = 64,
		ram_block1a_29.port_a_logical_ram_width = 32,
		ram_block1a_29.port_a_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_29.port_b_address_clock = "clock0",
		ram_block1a_29.port_b_address_width = 6,
		ram_block1a_29.port_b_data_in_clock = "clock0",
		ram_block1a_29.port_b_data_out_clear = "none",
		ram_block1a_29.port_b_data_width = 1,
		ram_block1a_29.port_b_first_address = 0,
		ram_block1a_29.port_b_first_bit_number = 29,
		ram_block1a_29.port_b_last_address = 63,
		ram_block1a_29.port_b_logical_ram_depth = 64,
		ram_block1a_29.port_b_logical_ram_width = 32,
		ram_block1a_29.port_b_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_29.port_b_read_enable_clock = "clock0",
		ram_block1a_29.port_b_write_enable_clock = "clock0",
		ram_block1a_29.power_up_uninitialized = "false",
		ram_block1a_29.ram_block_type = "AUTO",
		ram_block1a_29.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_30
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[5:0]}),
	.portadatain({data_a[30]}),
	.portadataout(wire_ram_block1a_30portadataout[0:0]),
	.portare(1'b1),
	.portawe(wren_a),
	.portbaddr({address_b_wire[5:0]}),
	.portbdatain({data_b[30]}),
	.portbdataout(wire_ram_block1a_30portbdataout[0:0]),
	.portbre(1'b1),
	.portbwe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_30.clk0_core_clock_enable = "none",
		ram_block1a_30.clk0_input_clock_enable = "none",
		ram_block1a_30.connectivity_checking = "OFF",
		ram_block1a_30.init_file = "../bootrom.hex",
		ram_block1a_30.init_file_layout = "port_a",
		ram_block1a_30.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_30.mem_init0 = 64'h00000181440CD498,
		ram_block1a_30.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_30.operation_mode = "bidir_dual_port",
		ram_block1a_30.port_a_address_width = 6,
		ram_block1a_30.port_a_data_out_clear = "none",
		ram_block1a_30.port_a_data_width = 1,
		ram_block1a_30.port_a_first_address = 0,
		ram_block1a_30.port_a_first_bit_number = 30,
		ram_block1a_30.port_a_last_address = 63,
		ram_block1a_30.port_a_logical_ram_depth = 64,
		ram_block1a_30.port_a_logical_ram_width = 32,
		ram_block1a_30.port_a_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_30.port_b_address_clock = "clock0",
		ram_block1a_30.port_b_address_width = 6,
		ram_block1a_30.port_b_data_in_clock = "clock0",
		ram_block1a_30.port_b_data_out_clear = "none",
		ram_block1a_30.port_b_data_width = 1,
		ram_block1a_30.port_b_first_address = 0,
		ram_block1a_30.port_b_first_bit_number = 30,
		ram_block1a_30.port_b_last_address = 63,
		ram_block1a_30.port_b_logical_ram_depth = 64,
		ram_block1a_30.port_b_logical_ram_width = 32,
		ram_block1a_30.port_b_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_30.port_b_read_enable_clock = "clock0",
		ram_block1a_30.port_b_write_enable_clock = "clock0",
		ram_block1a_30.power_up_uninitialized = "false",
		ram_block1a_30.ram_block_type = "AUTO",
		ram_block1a_30.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_31
	( 
	.clk0(clock0),
	.portaaddr({address_a_wire[5:0]}),
	.portadatain({data_a[31]}),
	.portadataout(wire_ram_block1a_31portadataout[0:0]),
	.portare(1'b1),
	.portawe(wren_a),
	.portbaddr({address_b_wire[5:0]}),
	.portbdatain({data_b[31]}),
	.portbdataout(wire_ram_block1a_31portbdataout[0:0]),
	.portbre(1'b1),
	.portbwe(wren_b)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena0(1'b1),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}})
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_31.clk0_core_clock_enable = "none",
		ram_block1a_31.clk0_input_clock_enable = "none",
		ram_block1a_31.connectivity_checking = "OFF",
		ram_block1a_31.init_file = "../bootrom.hex",
		ram_block1a_31.init_file_layout = "port_a",
		ram_block1a_31.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_31.mem_init0 = 64'h0000001888010002,
		ram_block1a_31.mixed_port_feed_through_mode = "dont_care",
		ram_block1a_31.operation_mode = "bidir_dual_port",
		ram_block1a_31.port_a_address_width = 6,
		ram_block1a_31.port_a_data_out_clear = "none",
		ram_block1a_31.port_a_data_width = 1,
		ram_block1a_31.port_a_first_address = 0,
		ram_block1a_31.port_a_first_bit_number = 31,
		ram_block1a_31.port_a_last_address = 63,
		ram_block1a_31.port_a_logical_ram_depth = 64,
		ram_block1a_31.port_a_logical_ram_width = 32,
		ram_block1a_31.port_a_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_31.port_b_address_clock = "clock0",
		ram_block1a_31.port_b_address_width = 6,
		ram_block1a_31.port_b_data_in_clock = "clock0",
		ram_block1a_31.port_b_data_out_clear = "none",
		ram_block1a_31.port_b_data_width = 1,
		ram_block1a_31.port_b_first_address = 0,
		ram_block1a_31.port_b_first_bit_number = 31,
		ram_block1a_31.port_b_last_address = 63,
		ram_block1a_31.port_b_logical_ram_depth = 64,
		ram_block1a_31.port_b_logical_ram_width = 32,
		ram_block1a_31.port_b_read_during_write_mode = "new_data_no_nbe_read",
		ram_block1a_31.port_b_read_enable_clock = "clock0",
		ram_block1a_31.port_b_write_enable_clock = "clock0",
		ram_block1a_31.power_up_uninitialized = "false",
		ram_block1a_31.ram_block_type = "AUTO",
		ram_block1a_31.lpm_type = "cycloneive_ram_block";
	assign
		address_a_wire = address_a,
		address_b_wire = address_b,
		q_a = {wire_ram_block1a_31portadataout[0], wire_ram_block1a_30portadataout[0], wire_ram_block1a_29portadataout[0], wire_ram_block1a_28portadataout[0], wire_ram_block1a_27portadataout[0], wire_ram_block1a_26portadataout[0], wire_ram_block1a_25portadataout[0], wire_ram_block1a_24portadataout[0], wire_ram_block1a_23portadataout[0], wire_ram_block1a_22portadataout[0], wire_ram_block1a_21portadataout[0], wire_ram_block1a_20portadataout[0], wire_ram_block1a_19portadataout[0], wire_ram_block1a_18portadataout[0], wire_ram_block1a_17portadataout[0], wire_ram_block1a_16portadataout[0], wire_ram_block1a_15portadataout[0], wire_ram_block1a_14portadataout[0], wire_ram_block1a_13portadataout[0], wire_ram_block1a_12portadataout[0], wire_ram_block1a_11portadataout[0], wire_ram_block1a_10portadataout[0], wire_ram_block1a_9portadataout[0], wire_ram_block1a_8portadataout[0], wire_ram_block1a_7portadataout[0], wire_ram_block1a_6portadataout[0], wire_ram_block1a_5portadataout[0], wire_ram_block1a_4portadataout[0], wire_ram_block1a_3portadataout[0], wire_ram_block1a_2portadataout[0], wire_ram_block1a_1portadataout[0], wire_ram_block1a_0portadataout[0]},
		q_b = {wire_ram_block1a_31portbdataout[0], wire_ram_block1a_30portbdataout[0], wire_ram_block1a_29portbdataout[0], wire_ram_block1a_28portbdataout[0], wire_ram_block1a_27portbdataout[0], wire_ram_block1a_26portbdataout[0], wire_ram_block1a_25portbdataout[0], wire_ram_block1a_24portbdataout[0], wire_ram_block1a_23portbdataout[0], wire_ram_block1a_22portbdataout[0], wire_ram_block1a_21portbdataout[0], wire_ram_block1a_20portbdataout[0], wire_ram_block1a_19portbdataout[0], wire_ram_block1a_18portbdataout[0], wire_ram_block1a_17portbdataout[0], wire_ram_block1a_16portbdataout[0], wire_ram_block1a_15portbdataout[0], wire_ram_block1a_14portbdataout[0], wire_ram_block1a_13portbdataout[0], wire_ram_block1a_12portbdataout[0], wire_ram_block1a_11portbdataout[0], wire_ram_block1a_10portbdataout[0], wire_ram_block1a_9portbdataout[0], wire_ram_block1a_8portbdataout[0], wire_ram_block1a_7portbdataout[0], wire_ram_block1a_6portbdataout[0], wire_ram_block1a_5portbdataout[0], wire_ram_block1a_4portbdataout[0], wire_ram_block1a_3portbdataout[0], wire_ram_block1a_2portbdataout[0], wire_ram_block1a_1portbdataout[0], wire_ram_block1a_0portbdataout[0]};
	initial/*synthesis enable_verilog_initial_construct*/
 	begin
		$display("Warning: Memory initialization file ../bootrom.hex is not of the dimensions 64 X 32, the resulting memory design may not produce consistent simulation results.");
	end
endmodule //bootrom_altsyncram
//VALID FILE


// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on
module bootrom (
	address_a,
	address_b,
	clock,
	q_a,
	q_b)/* synthesis synthesis_clearbox = 1 */;

	input	[5:0]  address_a;
	input	[5:0]  address_b;
	input	  clock;
	output	[31:0]  q_a;
	output	[31:0]  q_b;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri1	  clock;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire [31:0] sub_wire0;
	wire [31:0] sub_wire1;
	wire  sub_wire2 = 1'h0;
	wire [31:0] sub_wire3 = 32'h0;
	wire [31:0] q_b = sub_wire0[31:0];
	wire [31:0] q_a = sub_wire1[31:0];

	bootrom_altsyncram	bootrom_altsyncram_component (
				.clock0 (clock),
				.wren_a (sub_wire2),
				.address_b (address_b),
				.data_b (sub_wire3),
				.wren_b (sub_wire2),
				.address_a (address_a),
				.data_a (sub_wire3),
				.q_b (sub_wire0),
				.q_a (sub_wire1));

endmodule

// ============================================================
// CNX file retrieval info
// ============================================================
// Retrieval info: PRIVATE: ADDRESSSTALL_A NUMERIC "0"
// Retrieval info: PRIVATE: ADDRESSSTALL_B NUMERIC "0"
// Retrieval info: PRIVATE: BYTEENA_ACLR_A NUMERIC "0"
// Retrieval info: PRIVATE: BYTEENA_ACLR_B NUMERIC "0"
// Retrieval info: PRIVATE: BYTE_ENABLE_A NUMERIC "0"
// Retrieval info: PRIVATE: BYTE_ENABLE_B NUMERIC "0"
// Retrieval info: PRIVATE: BYTE_SIZE NUMERIC "1"
// Retrieval info: PRIVATE: BlankMemory NUMERIC "0"
// Retrieval info: PRIVATE: CLOCK_ENABLE_INPUT_A NUMERIC "0"
// Retrieval info: PRIVATE: CLOCK_ENABLE_INPUT_B NUMERIC "0"
// Retrieval info: PRIVATE: CLOCK_ENABLE_OUTPUT_A NUMERIC "0"
// Retrieval info: PRIVATE: CLOCK_ENABLE_OUTPUT_B NUMERIC "0"
// Retrieval info: PRIVATE: CLRdata NUMERIC "0"
// Retrieval info: PRIVATE: CLRq NUMERIC "0"
// Retrieval info: PRIVATE: CLRrdaddress NUMERIC "0"
// Retrieval info: PRIVATE: CLRrren NUMERIC "0"
// Retrieval info: PRIVATE: CLRwraddress NUMERIC "0"
// Retrieval info: PRIVATE: CLRwren NUMERIC "0"
// Retrieval info: PRIVATE: Clock NUMERIC "0"
// Retrieval info: PRIVATE: Clock_A NUMERIC "0"
// Retrieval info: PRIVATE: Clock_B NUMERIC "0"
// Retrieval info: PRIVATE: IMPLEMENT_IN_LES NUMERIC "0"
// Retrieval info: PRIVATE: INDATA_ACLR_B NUMERIC "0"
// Retrieval info: PRIVATE: INDATA_REG_B NUMERIC "1"
// Retrieval info: PRIVATE: INIT_FILE_LAYOUT STRING "PORT_A"
// Retrieval info: PRIVATE: INIT_TO_SIM_X NUMERIC "0"
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Cyclone IV E"
// Retrieval info: PRIVATE: JTAG_ENABLED NUMERIC "0"
// Retrieval info: PRIVATE: JTAG_ID STRING "NONE"
// Retrieval info: PRIVATE: MAXIMUM_DEPTH NUMERIC "0"
// Retrieval info: PRIVATE: MEMSIZE NUMERIC "2048"
// Retrieval info: PRIVATE: MEM_IN_BITS NUMERIC "0"
// Retrieval info: PRIVATE: MIFfilename STRING "../bootrom.hex"
// Retrieval info: PRIVATE: OPERATION_MODE NUMERIC "3"
// Retrieval info: PRIVATE: OUTDATA_ACLR_B NUMERIC "0"
// Retrieval info: PRIVATE: OUTDATA_REG_B NUMERIC "0"
// Retrieval info: PRIVATE: RAM_BLOCK_TYPE NUMERIC "0"
// Retrieval info: PRIVATE: READ_DURING_WRITE_MODE_MIXED_PORTS NUMERIC "2"
// Retrieval info: PRIVATE: REGdata NUMERIC "1"
// Retrieval info: PRIVATE: REGq NUMERIC "0"
// Retrieval info: PRIVATE: REGrdaddress NUMERIC "0"
// Retrieval info: PRIVATE: REGrren NUMERIC "0"
// Retrieval info: PRIVATE: REGwraddress NUMERIC "1"
// Retrieval info: PRIVATE: REGwren NUMERIC "1"
// Retrieval info: PRIVATE: SYNTH_WRAPPER_GEN_POSTFIX STRING "1"
// Retrieval info: PRIVATE: USE_DIFF_CLKEN NUMERIC "0"
// Retrieval info: PRIVATE: UseDPRAM NUMERIC "1"
// Retrieval info: PRIVATE: VarWidth NUMERIC "0"
// Retrieval info: PRIVATE: WIDTH_READ_A NUMERIC "32"
// Retrieval info: PRIVATE: WIDTH_READ_B NUMERIC "32"
// Retrieval info: PRIVATE: WIDTH_WRITE_A NUMERIC "32"
// Retrieval info: PRIVATE: WIDTH_WRITE_B NUMERIC "32"
// Retrieval info: PRIVATE: WRADDR_ACLR_B NUMERIC "0"
// Retrieval info: PRIVATE: WRADDR_REG_B NUMERIC "1"
// Retrieval info: PRIVATE: WRCTRL_ACLR_B NUMERIC "0"
// Retrieval info: PRIVATE: enable NUMERIC "0"
// Retrieval info: PRIVATE: rden NUMERIC "0"
// Retrieval info: LIBRARY: altera_mf altera_mf.altera_mf_components.all
// Retrieval info: CONSTANT: ADDRESS_REG_B STRING "CLOCK0"
// Retrieval info: CONSTANT: CLOCK_ENABLE_INPUT_A STRING "BYPASS"
// Retrieval info: CONSTANT: CLOCK_ENABLE_INPUT_B STRING "BYPASS"
// Retrieval info: CONSTANT: CLOCK_ENABLE_OUTPUT_A STRING "BYPASS"
// Retrieval info: CONSTANT: CLOCK_ENABLE_OUTPUT_B STRING "BYPASS"
// Retrieval info: CONSTANT: INDATA_REG_B STRING "CLOCK0"
// Retrieval info: CONSTANT: INIT_FILE STRING "../bootrom.hex"
// Retrieval info: CONSTANT: INTENDED_DEVICE_FAMILY STRING "Cyclone IV E"
// Retrieval info: CONSTANT: LPM_TYPE STRING "altsyncram"
// Retrieval info: CONSTANT: NUMWORDS_A NUMERIC "64"
// Retrieval info: CONSTANT: NUMWORDS_B NUMERIC "64"
// Retrieval info: CONSTANT: OPERATION_MODE STRING "BIDIR_DUAL_PORT"
// Retrieval info: CONSTANT: OUTDATA_ACLR_A STRING "NONE"
// Retrieval info: CONSTANT: OUTDATA_ACLR_B STRING "NONE"
// Retrieval info: CONSTANT: OUTDATA_REG_A STRING "UNREGISTERED"
// Retrieval info: CONSTANT: OUTDATA_REG_B STRING "UNREGISTERED"
// Retrieval info: CONSTANT: POWER_UP_UNINITIALIZED STRING "FALSE"
// Retrieval info: CONSTANT: WIDTHAD_A NUMERIC "6"
// Retrieval info: CONSTANT: WIDTHAD_B NUMERIC "6"
// Retrieval info: CONSTANT: WIDTH_A NUMERIC "32"
// Retrieval info: CONSTANT: WIDTH_B NUMERIC "32"
// Retrieval info: CONSTANT: WIDTH_BYTEENA_A NUMERIC "1"
// Retrieval info: CONSTANT: WIDTH_BYTEENA_B NUMERIC "1"
// Retrieval info: CONSTANT: WRCONTROL_WRADDRESS_REG_B STRING "CLOCK0"
// Retrieval info: USED_PORT: address_a 0 0 6 0 INPUT NODEFVAL "address_a[5..0]"
// Retrieval info: USED_PORT: address_b 0 0 6 0 INPUT NODEFVAL "address_b[5..0]"
// Retrieval info: USED_PORT: clock 0 0 0 0 INPUT VCC "clock"
// Retrieval info: USED_PORT: q_a 0 0 32 0 OUTPUT NODEFVAL "q_a[31..0]"
// Retrieval info: USED_PORT: q_b 0 0 32 0 OUTPUT NODEFVAL "q_b[31..0]"
// Retrieval info: CONNECT: @address_a 0 0 6 0 address_a 0 0 6 0
// Retrieval info: CONNECT: @address_b 0 0 6 0 address_b 0 0 6 0
// Retrieval info: CONNECT: @clock0 0 0 0 0 clock 0 0 0 0
// Retrieval info: CONNECT: @data_a 0 0 32 0 GND 0 0 32 0
// Retrieval info: CONNECT: @data_b 0 0 32 0 GND 0 0 32 0
// Retrieval info: CONNECT: @wren_a 0 0 0 0 GND 0 0 0 0
// Retrieval info: CONNECT: @wren_b 0 0 0 0 GND 0 0 0 0
// Retrieval info: CONNECT: q_a 0 0 32 0 @q_a 0 0 32 0
// Retrieval info: CONNECT: q_b 0 0 32 0 @q_b 0 0 32 0
// Retrieval info: GEN_FILE: TYPE_NORMAL bootrom.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL bootrom.inc FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL bootrom.cmp FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL bootrom.bsf FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL bootrom_inst.v FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL bootrom_bb.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL bootrom_syn.v TRUE
// Retrieval info: LIB_FILE: altera_mf
