#!/usr/bin/env python
import argparse
import os
import sys

MODULE_PATH = '%INSTALL_PATH%/lib'
MODULES = 'vpi_uart vpi_debug_stub vpi_spislave'.split()
ROM_PATH = '%INSTALL_PATH%/lib/'
DEFAULT_ROM = 'bootrom.hex'

def main(args):
    parser = argparse.ArgumentParser(description = 'Oldland RTL Simluation wrapper')
    parser.add_argument('--bootrom', help = 'bootrom file in %INSTALL_PATH%/lib to use')
    parser.add_argument('--interactive', help = 'start in interactive mode',
                        action = 'store_true')
    parser.add_argument('--ramfile', help = 'file to preload onchip ram with')
    parser.add_argument('--sdcard', help = 'file to use as SD card image')
    parser.add_argument('--debug', help = 'enable trace debugging',
                        action = 'store_true')
    opts = parser.parse_args(args)

    rom_file = '{0}{1}'.format(ROM_PATH,
                                opts.bootrom if opts.bootrom else DEFAULT_ROM)
    cmd = ['/usr/bin/vvp', '-n',
           '-M{0}'.format(MODULE_PATH)] + ['-m{0}'.format(m) for m in MODULES] + \
          ['%INSTALL_PATH%/lib/keynsham.vvp', '-lxt2', '+romfile={0}'.format(rom_file)]
    if opts.interactive:
        cmd += ['+interactive']
    if opts.debug:
        cmd += ['+debug']
    if opts.ramfile:
        cmd += ['+ramfile={0}'.format(opts.ramfile)]
    if opts.sdcard:
        cmd += ['+sdcard={0}'.format(opts.sdcard)]
    try:
        os.execv('/usr/bin/vvp', cmd)
    except KeyboardInterrupt:
        pass

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
